# This file allows you to configure Streamlit's behavior.
# For more information, see: https://docs.streamlit.io/library/advanced-features/configuration

# The settings below are particularly useful for local development with Docker.
# Uncomment them to enable features like running without opening a browser tab
# and automatically rerunning the script on file changes.

#[server]
# Headless mode, so Streamlit doesn't open a browser window.
#headless = true

# Automatically rerun the script when the source file is saved.
#runOnSave = true

# Use polling for file changes, which is required for some Docker setups (e.g., on Windows).
#fileWatcherType = "poll"
